version: "3"
services:
  personal_budget-mysql:
    image: mysql:8.0.25
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=quevedodb
      - MYSQL_USER=quevedo
      - MYSQL_PASSWORD=quevedo
      - MYSQL_ROOT_PASSWORD=quevedo
    volumes:
      - personal_budget-data:/var/lib/mysql
  personal_budget-wildfly:
    build:
      dockerfile: Dockerfile
      context: src
    depends_on:
      - personal_budget-mysql
    ports:
      - 8080:8080
      - 9990:9990
      - 8787:8787
    volumes:
      - ./JPAentity/target:/opt/jboss/wildfly/standalone/deployments
volumes:
  personal_budget-data: